version: '2'
services:
    stockmanagement-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/StockManagement/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=StockManagement
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
