version: '2'
services:
    addressandthirdmanagement-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/AddressAndThirdManagement/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=AddressAndThirdManagement
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
